services:
  backend:
    build: ./backend
    ports:
    - "8000:8000"
    # Las variables vienen del .env raíz y se pasan al contenedor
    env_file: .env
    volumes:
    - ./backend:/app #no tengo que reiniciar docker si modifico el main

  frontend:
    build: ./frontend
    env_file: .env
    ports:
    - "5173:5173"
    depends_on:
    - backend
    volumes:
    - ./frontend:/app #no tengo que reiniciar docker si modifico el main
    - /app/node_modules #protege las dependencias internas del contenedor